require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Question = require('../models/Question');

const questions = [
  // ========== AMAZON ==========
  { title: 'Two Sum', difficulty: 'Easy', topic: 'Arrays', companies: ['Amazon', 'Google', 'Microsoft'], frequency: 95, rounds: ['Round 1', 'Online Test'], leetcodeLink: 'https://leetcode.com/problems/two-sum/', solution: { explanation: 'Use a hash map to store complement values.', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', followUpTips: 'Amazon often asks: What if array is sorted? What if multiple valid answers?' } },
  { title: 'Longest Substring Without Repeating Characters', difficulty: 'Medium', topic: 'Strings', companies: ['Amazon', 'Microsoft', 'Google'], frequency: 88, rounds: ['Round 1', 'Round 2'], leetcodeLink: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', solution: { explanation: 'Sliding window with a set to track characters.', timeComplexity: 'O(n)', spaceComplexity: 'O(min(m,n))', followUpTips: 'Amazon follow-up: Handle Unicode characters' } },
  { title: 'Number of Islands', difficulty: 'Medium', topic: 'Graphs', companies: ['Amazon', 'Google', 'Microsoft', 'Flipkart'], frequency: 85, rounds: ['Round 2', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/number-of-islands/', solution: { explanation: 'BFS/DFS to mark connected land cells as visited.', timeComplexity: 'O(m*n)', spaceComplexity: 'O(m*n)', followUpTips: 'Amazon asks: Can you solve without modifying input? Union-Find approach?' } },
  { title: 'LRU Cache', difficulty: 'Medium', topic: 'Design', companies: ['Amazon', 'Google', 'Microsoft', 'Flipkart'], frequency: 82, rounds: ['Round 2', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/lru-cache/', solution: { explanation: 'Use HashMap + Doubly Linked List for O(1) operations.', timeComplexity: 'O(1)', spaceComplexity: 'O(capacity)', followUpTips: 'Amazon: Implement LFU Cache. What if concurrent access?' } },
  { title: 'Word Break', difficulty: 'Medium', topic: 'Dynamic Programming', companies: ['Amazon', 'Google'], frequency: 78, rounds: ['Round 2', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/word-break/', solution: { explanation: 'DP with boolean array, check all substrings.', timeComplexity: 'O(n^2)', spaceComplexity: 'O(n)', followUpTips: 'Return all possible sentences (Word Break II)' } },
  { title: 'Trapping Rain Water', difficulty: 'Hard', topic: 'Arrays', companies: ['Amazon', 'Google', 'Microsoft'], frequency: 76, rounds: ['DSA Round', 'Final Round'], leetcodeLink: 'https://leetcode.com/problems/trapping-rain-water/', solution: { explanation: 'Two pointers tracking left/right max heights.', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'Amazon: 2D version of trapping rain water' } },
  { title: 'Copy List with Random Pointer', difficulty: 'Medium', topic: 'Linked Lists', companies: ['Amazon', 'Microsoft'], frequency: 73, rounds: ['Round 2'], leetcodeLink: 'https://leetcode.com/problems/copy-list-with-random-pointer/', solution: { explanation: 'Interweave original and cloned nodes, then separate.', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'Can you do it without extra space?' } },
  { title: 'Merge K Sorted Lists', difficulty: 'Hard', topic: 'Linked Lists', companies: ['Amazon', 'Google', 'Microsoft'], frequency: 71, rounds: ['Round 2', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/merge-k-sorted-lists/', solution: { explanation: 'Use min-heap (priority queue) to always get minimum.', timeComplexity: 'O(n log k)', spaceComplexity: 'O(k)', followUpTips: 'Divide and conquer approach is also valid' } },
  { title: 'Maximum Product Subarray', difficulty: 'Medium', topic: 'Dynamic Programming', companies: ['Amazon', 'Flipkart'], frequency: 68, rounds: ['Round 1'], leetcodeLink: 'https://leetcode.com/problems/maximum-product-subarray/', solution: { explanation: 'Track both max and min products (negatives can flip).', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'Handles zeros and negatives — important edge cases' } },
  { title: 'Serialize and Deserialize Binary Tree', difficulty: 'Hard', topic: 'Trees', companies: ['Amazon', 'Google', 'Microsoft'], frequency: 67, rounds: ['DSA Round', 'Final Round'], leetcodeLink: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', solution: { explanation: 'BFS level-order traversal with null markers.', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', followUpTips: 'Amazon: Why BFS vs DFS for serialization?' } },
  { title: 'K Closest Points to Origin', difficulty: 'Medium', topic: 'Heap', companies: ['Amazon', 'Google', 'Flipkart'], frequency: 72, rounds: ['Round 1', 'Online Test'], leetcodeLink: 'https://leetcode.com/problems/k-closest-points-to-origin/', solution: { explanation: 'Max-heap of size k, or QuickSelect for O(n) average.', timeComplexity: 'O(n log k)', spaceComplexity: 'O(k)', followUpTips: 'Amazon: Follow-up with streaming data' } },
  { title: 'Sliding Window Maximum', difficulty: 'Hard', topic: 'Sliding Window', companies: ['Amazon', 'Google'], frequency: 65, rounds: ['DSA Round'], leetcodeLink: 'https://leetcode.com/problems/sliding-window-maximum/', solution: { explanation: 'Monotonic deque to maintain window maximum.', timeComplexity: 'O(n)', spaceComplexity: 'O(k)', followUpTips: 'Classic deque problem — explain the monotonic property' } },
  { title: 'Meeting Rooms II', difficulty: 'Medium', topic: 'Intervals', companies: ['Amazon', 'Google', 'Microsoft'], frequency: 69, rounds: ['Round 2'], leetcodeLink: 'https://leetcode.com/problems/meeting-rooms-ii/', solution: { explanation: 'Min-heap tracking end times of ongoing meetings.', timeComplexity: 'O(n log n)', spaceComplexity: 'O(n)', followUpTips: 'Amazon Leadership Principle: Deliver Results — optimize room usage' } },
  { title: 'Binary Tree Level Order Traversal', difficulty: 'Medium', topic: 'Trees', companies: ['Amazon', 'Microsoft', 'Google'], frequency: 80, rounds: ['Round 1', 'Online Test'], leetcodeLink: 'https://leetcode.com/problems/binary-tree-level-order-traversal/', solution: { explanation: 'BFS with queue, collect nodes level by level.', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', followUpTips: 'Zigzag level order, right side view — all BFS variants' } },
  { title: 'Course Schedule', difficulty: 'Medium', topic: 'Graphs', companies: ['Amazon', 'Google', 'Microsoft'], frequency: 74, rounds: ['Round 2', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/course-schedule/', solution: { explanation: 'Topological sort (Kahn\'s BFS or DFS cycle detection).', timeComplexity: 'O(V+E)', spaceComplexity: 'O(V+E)', followUpTips: 'Amazon asks cycle detection in directed graphs often' } },

  // ========== GOOGLE ==========
  { title: 'Median of Two Sorted Arrays', difficulty: 'Hard', topic: 'Binary Search', companies: ['Google', 'Amazon', 'Microsoft'], frequency: 82, rounds: ['DSA Round', 'Final Round'], leetcodeLink: 'https://leetcode.com/problems/median-of-two-sorted-arrays/', solution: { explanation: 'Binary search on the smaller array to find partition.', timeComplexity: 'O(log(min(m,n)))', spaceComplexity: 'O(1)', followUpTips: 'Google asks this to test binary search mastery' } },
  { title: 'Word Ladder', difficulty: 'Hard', topic: 'BFS', companies: ['Google', 'Amazon'], frequency: 69, rounds: ['DSA Round'], leetcodeLink: 'https://leetcode.com/problems/word-ladder/', solution: { explanation: 'BFS with one character changes, using set for O(1) lookup.', timeComplexity: 'O(M^2 * N)', spaceComplexity: 'O(M^2 * N)', followUpTips: 'Bidirectional BFS reduces search space significantly' } },
  { title: 'Minimum Window Substring', difficulty: 'Hard', topic: 'Sliding Window', companies: ['Google', 'Amazon', 'Facebook'], frequency: 77, rounds: ['DSA Round', 'Round 2'], leetcodeLink: 'https://leetcode.com/problems/minimum-window-substring/', solution: { explanation: 'Sliding window with character frequency maps.', timeComplexity: 'O(|S|+|T|)', spaceComplexity: 'O(|S|+|T|)', followUpTips: 'Google loves sliding window problems at hard level' } },
  { title: 'Longest Palindromic Substring', difficulty: 'Medium', topic: 'Dynamic Programming', companies: ['Google', 'Amazon', 'Microsoft'], frequency: 79, rounds: ['Round 1', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/longest-palindromic-substring/', solution: { explanation: 'Expand around center approach or Manacher\'s algorithm.', timeComplexity: 'O(n^2) or O(n)', spaceComplexity: 'O(1) or O(n)', followUpTips: 'Google: Know Manacher\'s for O(n) solution' } },
  { title: 'Regular Expression Matching', difficulty: 'Hard', topic: 'Dynamic Programming', companies: ['Google', 'Facebook'], frequency: 63, rounds: ['DSA Round'], leetcodeLink: 'https://leetcode.com/problems/regular-expression-matching/', solution: { explanation: 'DP table where dp[i][j] = pattern p[:j] matches s[:i].', timeComplexity: 'O(m*n)', spaceComplexity: 'O(m*n)', followUpTips: 'Google tests DP state design skills' } },
  { title: 'Alien Dictionary', difficulty: 'Hard', topic: 'Topological Sort', companies: ['Google', 'Facebook', 'Microsoft'], frequency: 72, rounds: ['DSA Round', 'Final Round'], leetcodeLink: 'https://leetcode.com/problems/alien-dictionary/', solution: { explanation: 'Build graph from adjacent word comparisons, topological sort.', timeComplexity: 'O(C) where C is total length', spaceComplexity: 'O(1) since 26 chars', followUpTips: 'Graph construction from constraints is key insight' } },
  { title: 'Design Search Autocomplete System', difficulty: 'Hard', topic: 'Trie', companies: ['Google', 'Amazon', 'Microsoft'], frequency: 61, rounds: ['Final Round', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/design-search-autocomplete-system/', solution: { explanation: 'Trie with sentence frequencies, maintain top-3 per node.', timeComplexity: 'O(n*l) build, O(p) search', spaceComplexity: 'O(n*l)', followUpTips: 'Real Google product design — mention caching strategies' } },
  { title: 'Jump Game II', difficulty: 'Medium', topic: 'Greedy', companies: ['Google', 'Amazon'], frequency: 74, rounds: ['Round 2', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/jump-game-ii/', solution: { explanation: 'Greedy: track farthest reachable at each jump level.', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'Google: prove greedy works with induction' } },
  { title: 'Longest Consecutive Sequence', difficulty: 'Medium', topic: 'Hash Set', companies: ['Google', 'Amazon', 'Facebook'], frequency: 76, rounds: ['Round 1', 'Online Test'], leetcodeLink: 'https://leetcode.com/problems/longest-consecutive-sequence/', solution: { explanation: 'HashSet, only start counting from sequence beginnings.', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', followUpTips: 'O(n) constraint makes sorting solution invalid' } },
  { title: 'Reconstruct Itinerary', difficulty: 'Hard', topic: 'Eulerian Path', companies: ['Google', 'Amazon'], frequency: 58, rounds: ['DSA Round'], leetcodeLink: 'https://leetcode.com/problems/reconstruct-itinerary/', solution: { explanation: 'Hierholzer\'s algorithm for Eulerian path in directed graph.', timeComplexity: 'O(E log E)', spaceComplexity: 'O(E)', followUpTips: 'Eulerian path — ensure lexicographic ordering via sorted adjacency' } },
  { title: 'Burst Balloons', difficulty: 'Hard', topic: 'Dynamic Programming', companies: ['Google', 'Facebook'], frequency: 55, rounds: ['DSA Round'], leetcodeLink: 'https://leetcode.com/problems/burst-balloons/', solution: { explanation: 'Interval DP: think which balloon to burst last in range.', timeComplexity: 'O(n^3)', spaceComplexity: 'O(n^2)', followUpTips: 'Counter-intuitive DP direction — think last burst not first' } },

  // ========== MICROSOFT ==========
  { title: 'Reverse Linked List', difficulty: 'Easy', topic: 'Linked Lists', companies: ['Microsoft', 'Amazon', 'TCS', 'Wipro'], frequency: 90, rounds: ['Round 1', 'Online Test'], leetcodeLink: 'https://leetcode.com/problems/reverse-linked-list/', solution: { explanation: 'Iterative: prev, curr, next pointers. Or recursive.', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'Microsoft: Reverse in groups of K' } },
  { title: 'Validate Binary Search Tree', difficulty: 'Medium', topic: 'Trees', companies: ['Microsoft', 'Amazon', 'Google'], frequency: 83, rounds: ['Round 2', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/validate-binary-search-tree/', solution: { explanation: 'Pass min/max bounds recursively.', timeComplexity: 'O(n)', spaceComplexity: 'O(h)', followUpTips: 'Microsoft loves tree traversal and BST properties' } },
  { title: 'Maximum Depth of Binary Tree', difficulty: 'Easy', topic: 'Trees', companies: ['Microsoft', 'Amazon', 'TCS'], frequency: 88, rounds: ['Round 1', 'Online Test'], leetcodeLink: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', solution: { explanation: 'Recursive: 1 + max(left depth, right depth).', timeComplexity: 'O(n)', spaceComplexity: 'O(h)', followUpTips: 'Classic recursion — also know iterative BFS approach' } },
  { title: 'Lowest Common Ancestor of a Binary Tree', difficulty: 'Medium', topic: 'Trees', companies: ['Microsoft', 'Amazon', 'Google', 'Flipkart'], frequency: 79, rounds: ['Round 2', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/', solution: { explanation: 'Recurse: if node found or splits the path, it\'s LCA.', timeComplexity: 'O(n)', spaceComplexity: 'O(h)', followUpTips: 'Microsoft: LCA in BST (can use BST property for O(h))' } },
  { title: 'Spiral Matrix', difficulty: 'Medium', topic: 'Arrays', companies: ['Microsoft', 'Amazon', 'Google'], frequency: 75, rounds: ['Round 1', 'Round 2'], leetcodeLink: 'https://leetcode.com/problems/spiral-matrix/', solution: { explanation: 'Boundary-based traversal: top, right, bottom, left.', timeComplexity: 'O(m*n)', spaceComplexity: 'O(1)', followUpTips: 'Microsoft: Spiral Matrix II (fill), rotate matrix' } },
  { title: 'Implement Trie', difficulty: 'Medium', topic: 'Trie', companies: ['Microsoft', 'Google', 'Amazon'], frequency: 72, rounds: ['Round 2', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/implement-trie-prefix-tree/', solution: { explanation: 'Array[26] of TrieNode children, isEnd flag.', timeComplexity: 'O(m) per op', spaceComplexity: 'O(m*n)', followUpTips: 'Microsoft: Wildcard search in Trie' } },
  { title: 'Find Median from Data Stream', difficulty: 'Hard', topic: 'Heap', companies: ['Microsoft', 'Amazon', 'Google'], frequency: 68, rounds: ['DSA Round', 'Final Round'], leetcodeLink: 'https://leetcode.com/problems/find-median-from-data-stream/', solution: { explanation: 'Two heaps: max-heap for lower half, min-heap for upper half.', timeComplexity: 'O(log n) add, O(1) find', spaceComplexity: 'O(n)', followUpTips: 'Classic two-heap problem — rebalance after each insertion' } },
  { title: 'Decode Ways', difficulty: 'Medium', topic: 'Dynamic Programming', companies: ['Microsoft', 'Amazon', 'Facebook'], frequency: 74, rounds: ['Round 1', 'Round 2'], leetcodeLink: 'https://leetcode.com/problems/decode-ways/', solution: { explanation: 'DP: dp[i] = ways to decode s[:i]. Handle \'0\' carefully.', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', followUpTips: 'Microsoft: Decode Ways II with \'*\' wildcard' } },
  { title: 'Clone Graph', difficulty: 'Medium', topic: 'Graphs', companies: ['Microsoft', 'Amazon', 'Google'], frequency: 71, rounds: ['Round 2', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/clone-graph/', solution: { explanation: 'DFS/BFS with HashMap mapping original to clone nodes.', timeComplexity: 'O(V+E)', spaceComplexity: 'O(V)', followUpTips: 'Hash map crucial to handle cycles' } },

  // ========== TCS NQT ==========
  { title: 'Find Missing Number', difficulty: 'Easy', topic: 'Arrays', companies: ['TCS', 'Wipro', 'Infosys', 'Cognizant'], frequency: 92, rounds: ['Online Test', 'Round 1'], leetcodeLink: 'https://leetcode.com/problems/missing-number/', solution: { explanation: 'XOR all numbers with indices, or use sum formula n*(n+1)/2.', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'TCS NQT favorite — also know cyclic sort approach' } },
  { title: 'Fibonacci Number', difficulty: 'Easy', topic: 'Dynamic Programming', companies: ['TCS', 'Wipro', 'Infosys', 'Capgemini'], frequency: 89, rounds: ['Online Test', 'Round 1'], leetcodeLink: 'https://leetcode.com/problems/fibonacci-number/', solution: { explanation: 'Iterative O(n) or matrix exponentiation O(log n).', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'TCS often asks Fibonacci with memoization or print first n terms' } },
  { title: 'Palindrome Number', difficulty: 'Easy', topic: 'Strings', companies: ['TCS', 'Wipro', 'Infosys', 'Cognizant', 'HCL'], frequency: 91, rounds: ['Online Test'], leetcodeLink: 'https://leetcode.com/problems/palindrome-number/', solution: { explanation: 'Reverse half the number and compare. Handle negatives.', timeComplexity: 'O(log n)', spaceComplexity: 'O(1)', followUpTips: 'Without converting to string — TCS NQT constraint' } },
  { title: 'Reverse String', difficulty: 'Easy', topic: 'Strings', companies: ['TCS', 'Wipro', 'Infosys', 'Capgemini', 'HCL', 'Tech Mahindra'], frequency: 88, rounds: ['Online Test', 'Round 1'], leetcodeLink: 'https://leetcode.com/problems/reverse-string/', solution: { explanation: 'Two pointers from both ends, swap.', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'TCS: Also reverse words in a sentence' } },
  { title: 'Remove Duplicates from Sorted Array', difficulty: 'Easy', topic: 'Arrays', companies: ['TCS', 'Wipro', 'Infosys', 'Accenture'], frequency: 87, rounds: ['Online Test', 'Round 1'], leetcodeLink: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/', solution: { explanation: 'Two pointers: slow tracks unique, fast explores.', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'In-place operation — TCS NQT frequently tests this' } },
  { title: 'Sort an Array', difficulty: 'Medium', topic: 'Sorting', companies: ['TCS', 'Wipro', 'Infosys', 'Cognizant', 'Accenture'], frequency: 85, rounds: ['Online Test', 'Round 1'], leetcodeLink: 'https://leetcode.com/problems/sort-an-array/', solution: { explanation: 'Merge Sort for stable O(n log n). Know Quick Sort too.', timeComplexity: 'O(n log n)', spaceComplexity: 'O(n)', followUpTips: 'TCS asks to implement sorting without library functions' } },
  { title: 'Search in Rotated Sorted Array', difficulty: 'Medium', topic: 'Binary Search', companies: ['TCS', 'Amazon', 'Google', 'Microsoft'], frequency: 81, rounds: ['Round 1', 'Round 2'], leetcodeLink: 'https://leetcode.com/problems/search-in-rotated-sorted-array/', solution: { explanation: 'Modified binary search: determine which half is sorted.', timeComplexity: 'O(log n)', spaceComplexity: 'O(1)', followUpTips: 'TCS NQT advanced section — understand pivot finding' } },
  { title: 'Valid Parentheses', difficulty: 'Easy', topic: 'Stack', companies: ['TCS', 'Wipro', 'Amazon', 'Microsoft', 'Google'], frequency: 90, rounds: ['Online Test', 'Round 1'], leetcodeLink: 'https://leetcode.com/problems/valid-parentheses/', solution: { explanation: 'Stack: push open brackets, pop when close bracket matches.', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', followUpTips: 'TCS: Also generate all valid parentheses (backtracking)' } },
  { title: 'Best Time to Buy and Sell Stock', difficulty: 'Easy', topic: 'Arrays', companies: ['TCS', 'Wipro', 'Amazon', 'Google', 'Flipkart'], frequency: 91, rounds: ['Online Test', 'Round 1'], leetcodeLink: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', solution: { explanation: 'Track min price and max profit in single pass.', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'TCS: Buy/sell multiple times (Stock II), with cooldown (III)' } },
  { title: 'Linked List Cycle', difficulty: 'Easy', topic: 'Linked Lists', companies: ['TCS', 'Wipro', 'Infosys', 'Cognizant'], frequency: 88, rounds: ['Round 1', 'Online Test'], leetcodeLink: 'https://leetcode.com/problems/linked-list-cycle/', solution: { explanation: 'Floyd\'s Tortoise and Hare: slow/fast pointers.', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'TCS: Find cycle start node (Floyd\'s part 2)' } },

  // ========== WIPRO/INFOSYS ==========
  { title: 'Counting Bits', difficulty: 'Easy', topic: 'Bit Manipulation', companies: ['Wipro', 'Infosys', 'TCS', 'Cognizant'], frequency: 82, rounds: ['Online Test'], leetcodeLink: 'https://leetcode.com/problems/counting-bits/', solution: { explanation: 'DP: bits[i] = bits[i>>1] + (i&1).', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', followUpTips: 'Bit manipulation basics — Wipro NTH common topic' } },
  { title: 'Maximum Subarray (Kadane\'s)', difficulty: 'Medium', topic: 'Dynamic Programming', companies: ['Infosys', 'TCS', 'Wipro', 'Cognizant', 'Capgemini'], frequency: 93, rounds: ['Online Test', 'Round 1'], leetcodeLink: 'https://leetcode.com/problems/maximum-subarray/', solution: { explanation: 'Kadane\'s: maxCurrent = max(num, maxCurrent + num).', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'Infosys Springboard must-know — also return the subarray' } },
  { title: 'Rotate Array', difficulty: 'Medium', topic: 'Arrays', companies: ['Wipro', 'Infosys', 'TCS', 'Accenture'], frequency: 84, rounds: ['Online Test', 'Round 1'], leetcodeLink: 'https://leetcode.com/problems/rotate-array/', solution: { explanation: 'Reverse entire array, then reverse first k, then rest.', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'In-place O(1) space — the reversal trick is key' } },
  { title: 'Contains Duplicate', difficulty: 'Easy', topic: 'Hash Set', companies: ['Infosys', 'Wipro', 'TCS', 'HCL'], frequency: 86, rounds: ['Online Test'], leetcodeLink: 'https://leetcode.com/problems/contains-duplicate/', solution: { explanation: 'HashSet: return true if element already in set.', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', followUpTips: 'Infosys: Find duplicates within k distance (Contains Duplicate II)' } },
  { title: 'Climbing Stairs', difficulty: 'Easy', topic: 'Dynamic Programming', companies: ['Infosys', 'TCS', 'Wipro', 'Capgemini'], frequency: 88, rounds: ['Online Test', 'Round 1'], leetcodeLink: 'https://leetcode.com/problems/climbing-stairs/', solution: { explanation: 'Fibonacci variant: dp[i] = dp[i-1] + dp[i-2].', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'Infosys: Steps of 1,2,3 simultaneously (Tribonacci)' } },

  // ========== FLIPKART/MEESHO ==========
  { title: 'Subarray Sum Equals K', difficulty: 'Medium', topic: 'Prefix Sum', companies: ['Flipkart', 'Amazon', 'Google'], frequency: 76, rounds: ['Round 1', 'Round 2'], leetcodeLink: 'https://leetcode.com/problems/subarray-sum-equals-k/', solution: { explanation: 'Prefix sum with HashMap: count[prefixSum - k].', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', followUpTips: 'Flipkart: Maximum subarray with sum exactly K' } },
  { title: 'Top K Frequent Elements', difficulty: 'Medium', topic: 'Heap', companies: ['Flipkart', 'Amazon', 'Google', 'Microsoft'], frequency: 78, rounds: ['Round 1', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/top-k-frequent-elements/', solution: { explanation: 'Min-heap of size k, or bucket sort O(n).', timeComplexity: 'O(n log k)', spaceComplexity: 'O(n)', followUpTips: 'Bucket sort gives O(n) — Flipkart often asks optimal approach' } },
  { title: 'Product of Array Except Self', difficulty: 'Medium', topic: 'Arrays', companies: ['Flipkart', 'Amazon', 'Google', 'Microsoft'], frequency: 79, rounds: ['Round 1', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/product-of-array-except-self/', solution: { explanation: 'Left pass then right pass — no division, no extra space.', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'No division operator constraint — key insight' } },
  { title: 'Daily Temperatures', difficulty: 'Medium', topic: 'Stack', companies: ['Flipkart', 'Amazon', 'Google'], frequency: 74, rounds: ['Round 2'], leetcodeLink: 'https://leetcode.com/problems/daily-temperatures/', solution: { explanation: 'Monotonic decreasing stack storing indices.', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', followUpTips: 'Next greater element pattern — useful in many Flipkart Qs' } },
  { title: 'Coin Change', difficulty: 'Medium', topic: 'Dynamic Programming', companies: ['Flipkart', 'Amazon', 'Google', 'Microsoft'], frequency: 77, rounds: ['Round 1', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/coin-change/', solution: { explanation: 'Unbounded knapsack DP: dp[i] = min coins to make amount i.', timeComplexity: 'O(amount * coins)', spaceComplexity: 'O(amount)', followUpTips: 'Classic BFS approach also works — Flipkart tests both' } },

  // ========== META/FACEBOOK ==========
  { title: 'Valid Anagram', difficulty: 'Easy', topic: 'Strings', companies: ['Meta', 'Amazon', 'Google'], frequency: 85, rounds: ['Online Test', 'Round 1'], leetcodeLink: 'https://leetcode.com/problems/valid-anagram/', solution: { explanation: 'Count character frequencies with array[26] or HashMap.', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'Meta: Unicode characters, streaming input variations' } },
  { title: 'Group Anagrams', difficulty: 'Medium', topic: 'Hash Map', companies: ['Meta', 'Amazon', 'Google'], frequency: 80, rounds: ['Round 1', 'Round 2'], leetcodeLink: 'https://leetcode.com/problems/group-anagrams/', solution: { explanation: 'Sort each word as key, group by key in HashMap.', timeComplexity: 'O(n * k log k)', spaceComplexity: 'O(n*k)', followUpTips: 'Meta: Use character count array as key for O(n*k)' } },
  { title: 'Accounts Merge', difficulty: 'Medium', topic: 'Union Find', companies: ['Meta', 'Amazon', 'Google'], frequency: 68, rounds: ['Round 2', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/accounts-merge/', solution: { explanation: 'Union-Find: union emails sharing an account.', timeComplexity: 'O(n * alpha(n))', spaceComplexity: 'O(n)', followUpTips: 'Union-Find with path compression and union by rank' } },
  { title: 'Nested List Weight Sum', difficulty: 'Medium', topic: 'DFS', companies: ['Meta', 'Amazon', 'Google'], frequency: 62, rounds: ['Round 2'], leetcodeLink: 'https://leetcode.com/problems/nested-list-weight-sum/', solution: { explanation: 'DFS with depth multiplier for each nesting level.', timeComplexity: 'O(n)', spaceComplexity: 'O(d)', followUpTips: 'Meta: Nested List Weight Sum II (inverse weighting)' } },

  // ========== ZOHO ==========
  { title: 'Implement Stack Using Queues', difficulty: 'Easy', topic: 'Stack', companies: ['Zoho', 'TCS', 'Wipro'], frequency: 78, rounds: ['Round 1', 'Online Test'], leetcodeLink: 'https://leetcode.com/problems/implement-stack-using-queues/', solution: { explanation: 'Push: enqueue and rotate all previous elements.', timeComplexity: 'O(n) push', spaceComplexity: 'O(n)', followUpTips: 'Zoho: Implement Queue using Stacks (two-stack approach)' } },
  { title: 'Rotate Image', difficulty: 'Medium', topic: 'Arrays', companies: ['Zoho', 'Amazon', 'Microsoft', 'Google'], frequency: 76, rounds: ['Round 1', 'Round 2'], leetcodeLink: 'https://leetcode.com/problems/rotate-image/', solution: { explanation: 'Transpose then reverse each row (or reverse then transpose for CCW).', timeComplexity: 'O(n^2)', spaceComplexity: 'O(1)', followUpTips: 'Zoho loves matrix manipulation problems' } },
  { title: 'Flatten Binary Tree to Linked List', difficulty: 'Medium', topic: 'Trees', companies: ['Zoho', 'Amazon', 'Microsoft'], frequency: 71, rounds: ['Round 2'], leetcodeLink: 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/', solution: { explanation: 'Morris traversal or reverse pre-order (right, left, root).', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'Zoho tests in-place tree modifications' } },

  // ========== ADDITIONAL MIXED ==========
  { title: 'Combination Sum', difficulty: 'Medium', topic: 'Backtracking', companies: ['Amazon', 'Google', 'Microsoft', 'Flipkart'], frequency: 77, rounds: ['Round 2', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/combination-sum/', solution: { explanation: 'Backtracking: include current element (allow repeat) or skip.', timeComplexity: 'O(N^(T/M+1))', spaceComplexity: 'O(T/M)', followUpTips: 'No duplicates: sort + skip same at same level' } },
  { title: 'House Robber', difficulty: 'Medium', topic: 'Dynamic Programming', companies: ['Amazon', 'Microsoft', 'Google', 'Flipkart', 'TCS'], frequency: 81, rounds: ['Round 1', 'DSA Round'], leetcodeLink: 'https://leetcode.com/problems/house-robber/', solution: { explanation: 'dp[i] = max(dp[i-2] + nums[i], dp[i-1]).', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'House Robber II (circular), III (binary tree)' } },
  { title: 'Find All Anagrams in a String', difficulty: 'Medium', topic: 'Sliding Window', companies: ['Google', 'Amazon', 'Facebook', 'Microsoft'], frequency: 74, rounds: ['Round 1', 'Round 2'], leetcodeLink: 'https://leetcode.com/problems/find-all-anagrams-in-a-string/', solution: { explanation: 'Fixed-size sliding window with character frequency comparison.', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', followUpTips: 'Array of 26 more efficient than HashMap for lowercase letters' } },
  { title: 'Diameter of Binary Tree', difficulty: 'Easy', topic: 'Trees', companies: ['Amazon', 'Google', 'Microsoft', 'Flipkart'], frequency: 80, rounds: ['Round 1', 'Online Test'], leetcodeLink: 'https://leetcode.com/problems/diameter-of-binary-tree/', solution: { explanation: 'For each node, diameter = leftHeight + rightHeight. Track global max.', timeComplexity: 'O(n)', spaceComplexity: 'O(h)', followUpTips: 'Note: diameter doesn\'t have to pass through root' } },
  { title: 'Path Sum III', difficulty: 'Medium', topic: 'Prefix Sum', companies: ['Amazon', 'Google', 'Microsoft'], frequency: 68, rounds: ['DSA Round'], leetcodeLink: 'https://leetcode.com/problems/path-sum-iii/', solution: { explanation: 'DFS with prefix sum hashmap — same as subarray sum = k.', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', followUpTips: 'Elegant combination of tree DFS and prefix sum technique' } }
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/placeprep');
    console.log('Connected to MongoDB');

    await Question.deleteMany({});
    console.log('Cleared existing questions');

    const inserted = await Question.insertMany(questions);
    console.log(`Seeded ${inserted.length} DSA questions`);

    await mongoose.disconnect();
    console.log('Done! Disconnected from MongoDB');
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seed();
