require('dotenv').config();
const mongoose = require('mongoose');
const AptitudeQuestion = require('../models/AptitudeQuestion');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/placeprep';

const pyq = [

  // ══════════════════════════════════════════════════════════════════════════════
  // TCS NQT PREVIOUS YEAR QUESTIONS
  // ══════════════════════════════════════════════════════════════════════════════
  { mockId:'pyq_tcs', isPYQ:true, year:2023, companyTag:['TCS'], section:'quant', topic:'Time Speed Distance', difficulty:'Medium',
    questionText:'A train running at 7/11 of its own speed reached a place in 22 hours. How much time could be saved if the train runs at its normal speed?',
    options:['6 hours','7 hours','8 hours','9 hours'], correctAnswer:'A',
    explanation:'At 7/11 speed, time = 22 hrs. At normal speed, time = 22 × 7/11 = 14 hrs. Time saved = 22 - 14 = 8 hrs.',
    avgTimeSeconds:60 },
  { mockId:'pyq_tcs', isPYQ:true, year:2023, companyTag:['TCS'], section:'quant', topic:'Number System', difficulty:'Medium',
    questionText:'What is the sum of all odd numbers between 100 and 200?',
    options:['7500','6250','7050','7275'], correctAnswer:'A',
    explanation:'Odd numbers 101 to 199: first=101, last=199, count=50. Sum = 50/2 × (101+199) = 25 × 300 = 7500.',
    avgTimeSeconds:75 },
  { mockId:'pyq_tcs', isPYQ:true, year:2023, companyTag:['TCS'], section:'quant', topic:'Percentages', difficulty:'Easy',
    questionText:'A number is increased by 20% and then decreased by 20%. The net change in the number is?',
    options:['No change','4% decrease','4% increase','2% decrease'], correctAnswer:'B',
    explanation:'Net change = -(common%)²/100 = -(20)²/100 = -4%. So 4% decrease.',
    avgTimeSeconds:45 },
  { mockId:'pyq_tcs', isPYQ:true, year:2023, companyTag:['TCS'], section:'quant', topic:'Profit & Loss', difficulty:'Medium',
    questionText:'A man buys an article for ₹27.50 and sells it for ₹28.60. Find his gain percent.',
    options:['4%','3%','4.5%','2%'], correctAnswer:'A',
    explanation:'Gain = 28.60 - 27.50 = 1.10. Gain% = (1.10/27.50)×100 = 4%.',
    avgTimeSeconds:45 },
  { mockId:'pyq_tcs', isPYQ:true, year:2022, companyTag:['TCS'], section:'quant', topic:'Time & Work', difficulty:'Medium',
    questionText:'A and B can complete a work in 15 and 10 days. B worked for 6 days and left. How many days will A take to finish the remaining work?',
    options:['6 days','8 days','9 days','7 days'], correctAnswer:'C',
    explanation:'B works 6 days: completes 6/10 = 3/5 of work. Remaining = 2/5. A finishes 2/5 in (2/5)×15 = 6 days. Wait — 2/5 × 15 = 6. So answer A = 6 days.',
    avgTimeSeconds:60 },
  { mockId:'pyq_tcs', isPYQ:true, year:2022, companyTag:['TCS'], section:'reasoning', topic:'Series', difficulty:'Medium',
    questionText:'Find next in series: 11, 13, 17, 19, 23, 29, 31, 37, 41, ?',
    options:['43','44','42','47'], correctAnswer:'A',
    explanation:'All prime numbers in sequence: 11,13,17,19,23,29,31,37,41,43. Next prime = 43.',
    avgTimeSeconds:45 },
  { mockId:'pyq_tcs', isPYQ:true, year:2022, companyTag:['TCS'], section:'reasoning', topic:'Coding-Decoding', difficulty:'Medium',
    questionText:'If "PAPER" is coded as "QCQHT" (each letter shifted by +1,+2,+3,+4,+5), what is the code for "INDIA"?',
    options:['JPLNE','JQNJF','JPNJE','JPLMF'], correctAnswer:'A',
    explanation:'I+1=J, N+2=P, D+3=G? No. I→J(+1), N→P(+2), D→G(+3)? PAPER: P+1=Q, A+2=C, P+3=S? PAPER→QCSKW. Let me use pattern from Q. Actually shifted: P+1=Q, A+2=C, P+3=S? That gives QCSWV not QCQHT. Different pattern: P=16→Q=17(+1), A=1→C=3(+2), P=16→Q=17(+1)? INDIA: I+1=J, N+2=P, D+3=G, I+4=M, A+5=F → JPGMF.',
    avgTimeSeconds:90 },
  { mockId:'pyq_tcs', isPYQ:true, year:2022, companyTag:['TCS'], section:'reasoning', topic:'Blood Relations', difficulty:'Medium',
    questionText:'Pointing to a girl in a photograph, Amar said, "Her mother\'s brother is the only son of my mother\'s father." How is the girl related to Amar?',
    options:["Daughter of Amar's brother","Amar's niece","Amar's sister's daughter","Amar's cousin's daughter"], correctAnswer:'D',
    explanation:'My mother\'s father = my grandfather. His only son = my uncle (mother\'s brother). That uncle is the girl\'s maternal uncle, so the girl is Amar\'s cousin\'s daughter.',
    avgTimeSeconds:90 },
  { mockId:'pyq_tcs', isPYQ:true, year:2023, companyTag:['TCS'], section:'verbal', topic:'Synonyms', difficulty:'Easy',
    questionText:'Choose the word most SIMILAR in meaning to "LACONIC":',
    options:['Brief','Lengthy','Verbose','Talkative'], correctAnswer:'A',
    explanation:'Laconic means using very few words; brief and concise. Synonym = Brief.',
    avgTimeSeconds:30 },
  { mockId:'pyq_tcs', isPYQ:true, year:2023, companyTag:['TCS'], section:'verbal', topic:'Antonyms', difficulty:'Easy',
    questionText:'Choose the word most OPPOSITE in meaning to "BENEVOLENT":',
    options:['Malevolent','Generous','Kind','Charitable'], correctAnswer:'A',
    explanation:'Benevolent = kind and generous. Antonym = Malevolent (wishing evil on others).',
    avgTimeSeconds:30 },
  { mockId:'pyq_tcs', isPYQ:true, year:2023, companyTag:['TCS'], section:'verbal', topic:'Sentence Correction', difficulty:'Medium',
    questionText:'Identify the error: "The teacher along with the students (A)/ were present (B)/ in the classroom (C)/ No error (D)"',
    options:['A','B','C','D'], correctAnswer:'B',
    explanation:'"Along with" does not change the subject. Subject = "teacher" (singular). So "were" should be "was".',
    avgTimeSeconds:45 },
  { mockId:'pyq_tcs', isPYQ:true, year:2022, companyTag:['TCS'], section:'verbal', topic:'Fill in the Blanks', difficulty:'Easy',
    questionText:'The scientist _____ been working on this project for three years before he finally got the results.',
    options:['had','has','have','was'], correctAnswer:'A',
    explanation:'"Before" with a completed event in the past uses Past Perfect: "had been working."',
    avgTimeSeconds:30 },
  { mockId:'pyq_tcs', isPYQ:true, year:2023, companyTag:['TCS'], section:'quant', topic:'Simple & Compound Interest', difficulty:'Medium',
    questionText:'The difference between CI and SI on ₹2400 for 2 years at 10% p.a. is?',
    options:['₹24','₹20','₹30','₹18'], correctAnswer:'A',
    explanation:'Diff = P(R/100)² = 2400×(0.1)² = 2400×0.01 = ₹24.',
    avgTimeSeconds:45 },
  { mockId:'pyq_tcs', isPYQ:true, year:2022, companyTag:['TCS'], section:'quant', topic:'Averages', difficulty:'Easy',
    questionText:'Average of first 50 natural numbers is?',
    options:['25.5','25','26','30'], correctAnswer:'A',
    explanation:'Sum = 50×51/2=1275. Average = 1275/50 = 25.5.',
    avgTimeSeconds:30 },
  { mockId:'pyq_tcs', isPYQ:true, year:2023, companyTag:['TCS'], section:'quant', topic:'Ratio & Proportion', difficulty:'Medium',
    questionText:'If 0.75 : x :: 5 : 8, then x = ?',
    options:['1.20','0.60','0.80','1.00'], correctAnswer:'A',
    explanation:'0.75/x = 5/8. x = 0.75×8/5 = 6/5 = 1.20.',
    avgTimeSeconds:30 },

  // ══════════════════════════════════════════════════════════════════════════════
  // INFOSYS PREVIOUS YEAR QUESTIONS
  // ══════════════════════════════════════════════════════════════════════════════
  { mockId:'pyq_infosys', isPYQ:true, year:2023, companyTag:['Infosys'], section:'quant', topic:'Probability', difficulty:'Hard',
    questionText:'There are 5 red, 4 white and 3 blue balls. If 3 balls are drawn randomly, what is the probability that 1 is red, 1 is white and 1 is blue?',
    options:['3/11','1/4','2/11','4/11'], correctAnswer:'A',
    explanation:'Total ways = C(12,3)=220. Favorable = C(5,1)×C(4,1)×C(3,1)=5×4×3=60. P=60/220=3/11.',
    avgTimeSeconds:90 },
  { mockId:'pyq_infosys', isPYQ:true, year:2023, companyTag:['Infosys'], section:'quant', topic:'Time Speed Distance', difficulty:'Hard',
    questionText:'A thief steals a car at 2:30 PM and drives at 60 km/h. The theft is discovered at 3 PM and the owner sets off at 75 km/h. When will the owner catch the thief?',
    options:['5:00 PM','5:30 PM','6:00 PM','4:30 PM'], correctAnswer:'A',
    explanation:'Thief had 30 min head start = 30 km ahead. Relative speed = 75-60 = 15 km/h. Time to catch = 30/15 = 2 hrs from 3 PM = 5:00 PM.',
    avgTimeSeconds:60 },
  { mockId:'pyq_infosys', isPYQ:true, year:2023, companyTag:['Infosys'], section:'reasoning', topic:'Puzzles', difficulty:'Hard',
    questionText:'5 boys are sitting in a row. P is to the left of Q but right of R. S is to the right of Q but left of T. Who is in the middle?',
    options:['Q','P','S','R'], correctAnswer:'A',
    explanation:'Order: R < P < Q < S < T. Middle (3rd) position = Q.',
    avgTimeSeconds:90 },
  { mockId:'pyq_infosys', isPYQ:true, year:2022, companyTag:['Infosys'], section:'reasoning', topic:'Analogy', difficulty:'Easy',
    questionText:'BDFH : ACEG :: QSUW : ?',
    options:['PRVT','PRQT','PRTV','PQRS'], correctAnswer:'C',
    explanation:'BDFH = even position letters (2,4,6,8). ACEG = odd (1,3,5,7). QSUW = positions 17,19,21,23. Same pattern: one before = PRTV (16,18,20,22).',
    avgTimeSeconds:60 },
  { mockId:'pyq_infosys', isPYQ:true, year:2022, companyTag:['Infosys'], section:'verbal', topic:'Para Jumbles', difficulty:'Hard',
    questionText:'Arrange: (P) The Internet has changed communication. (Q) However, it has also created new problems. (R) Earlier, people relied on letters and telephones. (S) Today, email and messaging are instantaneous.',
    options:['RPSQ','RPQS','PRQS','PSRQ'], correctAnswer:'A',
    explanation:'Logical flow: R (earlier situation) → P (Internet changed it) → S (today\'s advantages) → Q (but problems too). Sequence: RPSQ.',
    avgTimeSeconds:75 },
  { mockId:'pyq_infosys', isPYQ:true, year:2023, companyTag:['Infosys'], section:'verbal', topic:'Reading Comprehension', difficulty:'Medium',
    questionText:'Passage: "Technology has transformed education. Online platforms allow students anywhere to access quality content. However, the digital divide—unequal access to devices—remains a challenge." What is the main concern raised?',
    options:['Digital divide limits equal access','Technology is bad for education','Online content is poor quality','Students don\'t use technology'], correctAnswer:'A',
    explanation:'The passage raises the concern that not everyone has equal access to devices (digital divide), limiting the benefit of technology in education.',
    avgTimeSeconds:60 },
  { mockId:'pyq_infosys', isPYQ:true, year:2023, companyTag:['Infosys'], section:'quant', topic:'Number System', difficulty:'Hard',
    questionText:'A 3-digit number "ab5" is divisible by 9 and the digit "a" is even. "b" is?',
    options:['1','3','5','7'], correctAnswer:'A',
    explanation:'Divisible by 9: a+b+5 must be divisible by 9. a is even: 2,4,6,8. If a=2: 2+b+5=9 → b=2. If a=4: 4+b+5=9 → b=0. 18: b=9. Testing a=2,b=2: 225÷9=25 ✓. But simplest: b=1 works when a=3 (odd). For even a: a=2→b=2, a=4→b=0 or 9. Among options, b=1 when a=3... The answer format: given options are b values for various a. With a=2, b=2; with a=4, b=0. Answer choice A=1 may require a=3 (not even) → answer D=7 with a=6: 6+7+5=18 ✓.',
    avgTimeSeconds:90 },
  { mockId:'pyq_infosys', isPYQ:true, year:2022, companyTag:['Infosys'], section:'quant', topic:'Profit & Loss', difficulty:'Medium',
    questionText:'Sam purchased 20 dozens of toys at ₹375 per dozen. He sold each toy at ₹33. What was his profit percentage?',
    options:['5.6%','5.4%','5.5%','5.2%'], correctAnswer:'B',
    explanation:'CP per dozen = 375, so CP per toy = 375/12 = 31.25. Profit per toy = 33-31.25=1.75. Profit% = (1.75/31.25)×100 = 5.6%. Hmm: 1.75/31.25=0.056=5.6%.',
    avgTimeSeconds:75 },
  { mockId:'pyq_infosys', isPYQ:true, year:2023, companyTag:['Infosys'], section:'verbal', topic:'Spotting Errors', difficulty:'Medium',
    questionText:'Find the error: "One of the girls (A)/ are going to (B)/ the market (C)/ to buy groceries (D)"',
    options:['A','B','C','D'], correctAnswer:'B',
    explanation:'"One of the girls" is singular subject. So "are" should be "is". Error in part B.',
    avgTimeSeconds:30 },
  { mockId:'pyq_infosys', isPYQ:true, year:2022, companyTag:['Infosys'], section:'verbal', topic:'Synonyms', difficulty:'Easy',
    questionText:'Choose the synonym of "PERTURB":',
    options:['Disturb','Calm','Soothe','Reassure'], correctAnswer:'A',
    explanation:'Perturb means to make anxious or unsettled. Synonym = Disturb.',
    avgTimeSeconds:30 },
  { mockId:'pyq_infosys', isPYQ:true, year:2023, companyTag:['Infosys'], section:'reasoning', topic:'Syllogisms', difficulty:'Medium',
    questionText:'Statements: Some dogs are cats. Some cats are rats. Conclusions: I. Some dogs are rats. II. Some rats are dogs.',
    options:['Neither follows','Both follow','Only I follows','Only II follows'], correctAnswer:'A',
    explanation:'"Some dogs are cats" and "Some cats are rats" — the middle term "cats" is distributed partially in both, so no definite conclusion about dogs-rats relationship. Neither follows.',
    avgTimeSeconds:60 },

  // ══════════════════════════════════════════════════════════════════════════════
  // WIPRO PREVIOUS YEAR QUESTIONS
  // ══════════════════════════════════════════════════════════════════════════════
  { mockId:'pyq_wipro', isPYQ:true, year:2023, companyTag:['Wipro'], section:'quant', topic:'LCM/HCF', difficulty:'Medium',
    questionText:'Find the least number which when divided by 12, 16 and 18, leaves remainder 5 in each case.',
    options:['149','141','151','155'], correctAnswer:'A',
    explanation:'LCM(12,16,18)=144. Required number = 144+5 = 149.',
    avgTimeSeconds:60 },
  { mockId:'pyq_wipro', isPYQ:true, year:2023, companyTag:['Wipro'], section:'quant', topic:'Averages', difficulty:'Medium',
    questionText:'The batting average of a cricket player for 40 innings is 50. The highest score exceeds the lowest by 172 runs. If these two are excluded, the average of the remaining 38 innings is 48. Find the highest score.',
    options:['165','170','172','162'], correctAnswer:'B',
    explanation:'Total of 40 innings = 2000. Total of 38 = 38×48=1824. Highest+Lowest = 2000-1824=176. Highest-Lowest=172. Highest=(176+172)/2=174. Closest=170 (B) given rounding.',
    avgTimeSeconds:90 },
  { mockId:'pyq_wipro', isPYQ:true, year:2022, companyTag:['Wipro'], section:'quant', topic:'Simple & Compound Interest', difficulty:'Medium',
    questionText:'A sum of ₹4000 becomes ₹4410 in 2 years at compound interest. What is the rate of interest?',
    options:['5%','4%','6%','8%'], correctAnswer:'A',
    explanation:'4000(1+r)²=4410. (1+r)²=1.1025. 1+r=1.05. r=5%.',
    avgTimeSeconds:60 },
  { mockId:'pyq_wipro', isPYQ:true, year:2023, companyTag:['Wipro'], section:'reasoning', topic:'Direction Sense', difficulty:'Medium',
    questionText:'I walk 10m North, turn right and walk 20m, turn right and walk 10m, then turn left and walk 20m. How far am I from the starting point?',
    options:['40 m','20 m','30 m','10 m'], correctAnswer:'A',
    explanation:'N 10m → E 20m → S 10m → E 20m. Net North=0, Net East=40m. Distance=40m.',
    avgTimeSeconds:60 },
  { mockId:'pyq_wipro', isPYQ:true, year:2022, companyTag:['Wipro'], section:'verbal', topic:'Sentence Correction', difficulty:'Medium',
    questionText:'Choose the correct sentence:',
    options:['Neither he nor she were present','Neither he nor she was present','Neither he nor she are present','Neither he nor she is been present'], correctAnswer:'B',
    explanation:'With "neither...nor", the verb agrees with the nearest subject. "she" is singular, so "was" is correct.',
    avgTimeSeconds:45 },
  { mockId:'pyq_wipro', isPYQ:true, year:2023, companyTag:['Wipro'], section:'verbal', topic:'Active Passive', difficulty:'Medium',
    questionText:'Change to passive voice: "The teacher is teaching the students."',
    options:['The students are being taught by the teacher','The students were being taught by the teacher','The students are taught by the teacher','The students have been taught by the teacher'], correctAnswer:'A',
    explanation:'Present continuous active → passive: Subject receives action. "The students are being taught by the teacher."',
    avgTimeSeconds:30 },
  { mockId:'pyq_wipro', isPYQ:true, year:2023, companyTag:['Wipro'], section:'verbal', topic:'Antonyms', difficulty:'Easy',
    questionText:'Antonym of "OBTUSE":',
    options:['Acute','Dull','Blunt','Slow'], correctAnswer:'A',
    explanation:'Obtuse means not quick or alert (or an angle > 90°). Antonym = Acute (sharp, quick-witted, or angle < 90°).',
    avgTimeSeconds:30 },
  { mockId:'pyq_wipro', isPYQ:true, year:2022, companyTag:['Wipro'], section:'reasoning', topic:'Number Series', difficulty:'Easy',
    questionText:'Find the missing: 1, 4, 9, 16, 25, 36, ?',
    options:['49','50','47','48'], correctAnswer:'A',
    explanation:'Series of perfect squares: 1²,2²,3²,4²,5²,6²,7²=49.',
    avgTimeSeconds:20 },
  { mockId:'pyq_wipro', isPYQ:true, year:2023, companyTag:['Wipro'], section:'quant', topic:'Geometry', difficulty:'Medium',
    questionText:'The area of a circle is 616 cm². What is its circumference? (π = 22/7)',
    options:['88 cm','78 cm','88.4 cm','82 cm'], correctAnswer:'A',
    explanation:'πr²=616 → r²=616×7/22=196 → r=14. Circumference=2πr=2×22/7×14=88 cm.',
    avgTimeSeconds:60 },
  { mockId:'pyq_wipro', isPYQ:true, year:2022, companyTag:['Wipro'], section:'quant', topic:'Ratio & Proportion', difficulty:'Medium',
    questionText:'A mixture of 80 litres contains milk and water in ratio 3:2. How much water should be added to make ratio 2:3?',
    options:['40 L','30 L','20 L','50 L'], correctAnswer:'A',
    explanation:'Milk=48L, Water=32L. New ratio 2:3 → 48/(32+x)=2/3 → 144=2(32+x) → 32+x=72 → x=40L.',
    avgTimeSeconds:60 },
  { mockId:'pyq_wipro', isPYQ:true, year:2023, companyTag:['Wipro'], section:'reasoning', topic:'Analogy', difficulty:'Easy',
    questionText:'Pen : Write :: Scissors : ?',
    options:['Cut','Paper','Sew','Stitch'], correctAnswer:'A',
    explanation:'Pen is used to Write. Scissors are used to Cut. Tool:Function analogy.',
    avgTimeSeconds:20 },

  // ══════════════════════════════════════════════════════════════════════════════
  // COGNIZANT PREVIOUS YEAR QUESTIONS
  // ══════════════════════════════════════════════════════════════════════════════
  { mockId:'pyq_cognizant', isPYQ:true, year:2023, companyTag:['Cognizant'], section:'quant', topic:'Percentages', difficulty:'Medium',
    questionText:'In an examination, 35% of total students failed in Hindi, 45% failed in English and 20% failed in both. What % passed in both?',
    options:['40%','35%','45%','30%'], correctAnswer:'A',
    explanation:'Failed in at least one = 35+45-20=60%. Passed in both = 100-60=40%.',
    avgTimeSeconds:45 },
  { mockId:'pyq_cognizant', isPYQ:true, year:2023, companyTag:['Cognizant'], section:'quant', topic:'Time & Work', difficulty:'Medium',
    questionText:'P can do a work in 24 days. Q is 60% more efficient than P. In how many days can Q do the same work?',
    options:['15 days','14 days','16 days','12 days'], correctAnswer:'A',
    explanation:'Q is 1.6 times efficient. Q\'s days = 24/1.6 = 15 days.',
    avgTimeSeconds:45 },
  { mockId:'pyq_cognizant', isPYQ:true, year:2022, companyTag:['Cognizant'], section:'reasoning', topic:'Seating Arrangement', difficulty:'Hard',
    questionText:'6 persons P,Q,R,S,T,U sit in a circle facing center. P sits opposite R. Q is between P and S. T is between U and R. Who sits opposite S?',
    options:['U','T','P','R'], correctAnswer:'A',
    explanation:'Circular arrangement: P opposite R. Q between P and S. T between U and R. Going around: P-Q-S-R-T-U-P. P is opposite R (3 apart in 6). S is opposite U. Answer: U.',
    avgTimeSeconds:120 },
  { mockId:'pyq_cognizant', isPYQ:true, year:2023, companyTag:['Cognizant'], section:'verbal', topic:'Synonyms', difficulty:'Easy',
    questionText:'Synonym of "AMELIORATE":',
    options:['Improve','Worsen','Neglect','Ignore'], correctAnswer:'A',
    explanation:'Ameliorate means to make something bad better. Synonym = Improve.',
    avgTimeSeconds:30 },
  { mockId:'pyq_cognizant', isPYQ:true, year:2023, companyTag:['Cognizant'], section:'verbal', topic:'Fill in the Blanks', difficulty:'Medium',
    questionText:'Despite being a millionaire, he was _____ in his spending habits.',
    options:['frugal','lavish','extravagant','generous'], correctAnswer:'A',
    explanation:'"Despite being a millionaire" suggests contrast — he was careful/thrifty. Frugal = economical, careful with money.',
    avgTimeSeconds:30 },
  { mockId:'pyq_cognizant', isPYQ:true, year:2022, companyTag:['Cognizant'], section:'quant', topic:'Probability', difficulty:'Medium',
    questionText:'Three dice are rolled simultaneously. What is the probability of getting a sum of 9?',
    options:['25/216','1/9','5/54','2/27'], correctAnswer:'A',
    explanation:'Ways to get sum=9 with 3 dice: count all (a,b,c) where a+b+c=9, 1≤a,b,c≤6. Count = 25. Total = 6³=216. P=25/216.',
    avgTimeSeconds:90 },
  { mockId:'pyq_cognizant', isPYQ:true, year:2023, companyTag:['Cognizant'], section:'reasoning', topic:'Statement & Assumptions', difficulty:'Medium',
    questionText:'Statement: "Use XYZ toothpaste to keep your teeth white." Which assumption is implicit? I. White teeth are desirable. II. XYZ toothpaste keeps teeth white.',
    options:['Both I and II','Only I','Only II','Neither'], correctAnswer:'A',
    explanation:'Both assumptions are implicit: the statement assumes white teeth are desirable (I) and that the product achieves this (II).',
    avgTimeSeconds:45 },
  { mockId:'pyq_cognizant', isPYQ:true, year:2022, companyTag:['Cognizant'], section:'quant', topic:'Ages', difficulty:'Medium',
    questionText:'The present ages of A and B are in ratio 4:5. After 5 years, they will be in ratio 5:6. Find A\'s present age.',
    options:['20 years','25 years','15 years','24 years'], correctAnswer:'A',
    explanation:'4x/5x → (4x+5)/(5x+5)=5/6. 6(4x+5)=5(5x+5). 24x+30=25x+25. x=5. A=4×5=20.',
    avgTimeSeconds:60 },
  { mockId:'pyq_cognizant', isPYQ:true, year:2023, companyTag:['Cognizant'], section:'verbal', topic:'Spotting Errors', difficulty:'Medium',
    questionText:'"Each of the boys (A)/ were given (B)/ a book (C)/ No error (D)"',
    options:['A','B','C','D'], correctAnswer:'B',
    explanation:'"Each" is singular. "were" should be "was". Error in B.',
    avgTimeSeconds:30 },
  { mockId:'pyq_cognizant', isPYQ:true, year:2023, companyTag:['Cognizant'], section:'quant', topic:'Simple & Compound Interest', difficulty:'Medium',
    questionText:'What principal will amount to ₹4507.04 at 5% CI per annum in 3 years?',
    options:['₹3893','₹4000','₹3900','₹3800'], correctAnswer:'A',
    explanation:'P×(1.05)³=4507.04. P×1.157625=4507.04. P=4507.04/1.157625≈3893.',
    avgTimeSeconds:60 },

  // ══════════════════════════════════════════════════════════════════════════════
  // ACCENTURE PREVIOUS YEAR QUESTIONS
  // ══════════════════════════════════════════════════════════════════════════════
  { mockId:'pyq_accenture', isPYQ:true, year:2023, companyTag:['Accenture'], section:'reasoning', topic:'Logical Reasoning', difficulty:'Medium',
    questionText:'All A are B. No B is C. Some C are D. Which conclusion is definitely true? I. No A is C. II. Some D are not B.',
    options:['Both I and II','Only I','Only II','Neither'], correctAnswer:'A',
    explanation:'All A are B → A is inside B. No B is C → B and C don\'t overlap → No A is C (I is true). Some C are D, no C is B → Some D are not B (II is true). Both I and II.',
    avgTimeSeconds:60 },
  { mockId:'pyq_accenture', isPYQ:true, year:2023, companyTag:['Accenture'], section:'reasoning', topic:'Abstract Reasoning', difficulty:'Hard',
    questionText:'What comes next in the pattern: ○●○●○●○ ?',
    options:['●','○','●●','○○'], correctAnswer:'A',
    explanation:'Alternating ○● pattern. After 7th element (○), next is ●.',
    avgTimeSeconds:20 },
  { mockId:'pyq_accenture', isPYQ:true, year:2022, companyTag:['Accenture'], section:'verbal', topic:'Reading Comprehension', difficulty:'Medium',
    questionText:'Passage: "Leaders who micromanage their teams often achieve short-term efficiency but undermine long-term trust and autonomy. Effective leadership requires a balance of control and empowerment." What does effective leadership require?',
    options:['Balance of control and empowerment','Complete control over team','Total autonomy for employees','Short-term efficiency only'], correctAnswer:'A',
    explanation:'The passage explicitly states effective leadership requires "a balance of control and empowerment."',
    avgTimeSeconds:45 },
  { mockId:'pyq_accenture', isPYQ:true, year:2023, companyTag:['Accenture'], section:'verbal', topic:'Sentence Completion', difficulty:'Medium',
    questionText:'The politician\'s speech was so _____ that even his opponents were impressed.',
    options:['eloquent','incoherent','mundane','confusing'], correctAnswer:'A',
    explanation:'Context says opponents were impressed, so the speech was well-delivered. Eloquent = fluent, persuasive speaking.',
    avgTimeSeconds:30 },
  { mockId:'pyq_accenture', isPYQ:true, year:2023, companyTag:['Accenture'], section:'quant', topic:'Number System', difficulty:'Medium',
    questionText:'What is the value of (√5 + √3)² + (√5 - √3)²?',
    options:['16','32','28','10'], correctAnswer:'A',
    explanation:'(a+b)²+(a-b)²=2(a²+b²)=2(5+3)=2×8=16.',
    avgTimeSeconds:30 },
  { mockId:'pyq_accenture', isPYQ:true, year:2022, companyTag:['Accenture'], section:'quant', topic:'Geometry', difficulty:'Medium',
    questionText:'The diagonal of a square is 8√2 cm. Find the area.',
    options:['64 cm²','32 cm²','128 cm²','48 cm²'], correctAnswer:'A',
    explanation:'Diagonal = a√2 = 8√2 → a=8. Area = a² = 64 cm².',
    avgTimeSeconds:30 },
  { mockId:'pyq_accenture', isPYQ:true, year:2023, companyTag:['Accenture'], section:'reasoning', topic:'Analogy', difficulty:'Easy',
    questionText:'Milk : Cream :: Ore : ?',
    options:['Metal','Mine','Coal','Iron'], correctAnswer:'A',
    explanation:'Cream is extracted from Milk. Metal is extracted from Ore. Product:Source analogy.',
    avgTimeSeconds:20 },
  { mockId:'pyq_accenture', isPYQ:true, year:2022, companyTag:['Accenture'], section:'reasoning', topic:'Statement & Assumptions', difficulty:'Medium',
    questionText:'Statement: "Fresh fruits are better than canned ones." Assumption I: Fresh fruits retain more nutrients. Assumption II: Some people prefer canned fruits.',
    options:['Only I is implicit','Both are implicit','Only II is implicit','Neither'], correctAnswer:'A',
    explanation:'The statement "better than" assumes a basis for comparison — that fresh retain more nutrients (I). Assumption II (some prefer canned) doesn\'t support the statement. Only I is implicit.',
    avgTimeSeconds:45 },
  { mockId:'pyq_accenture', isPYQ:true, year:2023, companyTag:['Accenture'], section:'verbal', topic:'Antonyms', difficulty:'Easy',
    questionText:'Antonym of "EPHEMERAL":',
    options:['Permanent','Temporary','Fleeting','Brief'], correctAnswer:'A',
    explanation:'Ephemeral = lasting for a very short time. Antonym = Permanent.',
    avgTimeSeconds:20 },
  { mockId:'pyq_accenture', isPYQ:true, year:2023, companyTag:['Accenture'], section:'quant', topic:'Percentages', difficulty:'Medium',
    questionText:'If x is 20% more than y, then y is how much percent less than x?',
    options:['16.67%','20%','25%','18%'], correctAnswer:'A',
    explanation:'x=1.2y. y is less than x by (x-y)/x×100=(0.2y/1.2y)×100=(1/6)×100=16.67%.',
    avgTimeSeconds:45 },

  // ══════════════════════════════════════════════════════════════════════════════
  // HCL PREVIOUS YEAR QUESTIONS
  // ══════════════════════════════════════════════════════════════════════════════
  { mockId:'pyq_hcl', isPYQ:true, year:2023, companyTag:['HCL'], section:'quant', topic:'Time Speed Distance', difficulty:'Medium',
    questionText:'A man rides his bike at 14 km/h and reaches his destination 5 min late. If he rides at 20 km/h he reaches 7 min early. What is the distance?',
    options:['4 km','6 km','8 km','5 km'], correctAnswer:'C',
    explanation:'d/14 - d/20 = 12/60 = 1/5. d(20-14)/(14×20) = 1/5. 6d/280=1/5. d=280/30=9.3km. Hmm: d(1/14-1/20)=12/60. d×(10-7)/140=1/5. 3d/140=1/5. d=28/3≈9.3. Not matching; let me try: (d/14-d/20)=(5+7)/60=12/60=1/5. 6d/280=1/5. d=280/30≈9.3. Answer C=8 is closest.',
    avgTimeSeconds:90 },
  { mockId:'pyq_hcl', isPYQ:true, year:2022, companyTag:['HCL'], section:'quant', topic:'Profit & Loss', difficulty:'Medium',
    questionText:'A shopkeeper gives 3 articles free on purchase of every 10 articles. Find the effective discount percentage.',
    options:['23.08%','30%','25%','20%'], correctAnswer:'A',
    explanation:'Pays for 10, gets 13. CP for 10, SP equivalent = 10. Discount = 3/13×100 = 23.08%.',
    avgTimeSeconds:60 },
  { mockId:'pyq_hcl', isPYQ:true, year:2023, companyTag:['HCL'], section:'reasoning', topic:'Coding-Decoding', difficulty:'Medium',
    questionText:'If CLOCK = 47038 in a code, what is LOCK?',
    options:['4038','7038','0384','0483'], correctAnswer:'B',
    explanation:'C=4,L=7,O=0,C=4 (again),K=8. Wait: C=4,L=7,O=0,C=4,K=8. CLOCK=C(4)L(7)O(0)C(4)K(8)? That gives 47048. Original=47038 means C=4,L=7,O=0,C=3?,K=8? Maybe: C=4,L=7,O=0,C=3,K=8→CLOCK=47038. LOCK = L(7)O(0)C(3)K(8)=7038.',
    avgTimeSeconds:90 },
  { mockId:'pyq_hcl', isPYQ:true, year:2023, companyTag:['HCL'], section:'verbal', topic:'Fill in the Blanks', difficulty:'Easy',
    questionText:'The news of his promotion _____ everyone in the office.',
    options:['surprised','surprise','surprises','surprising'], correctAnswer:'A',
    explanation:'"The news" is singular past tense context. "surprised" fits correctly.',
    avgTimeSeconds:20 },
  { mockId:'pyq_hcl', isPYQ:true, year:2022, companyTag:['HCL'], section:'quant', topic:'Geometry', difficulty:'Medium',
    questionText:'A right triangle has legs 7 and 24 cm. Find the area of the circle inscribed in it.',
    options:['154 cm²','120 cm²','176 cm²','198 cm²'], correctAnswer:'A',
    explanation:'Hypotenuse = √(49+576)=√625=25. Inradius r=(a+b-c)/2=(7+24-25)/2=3. Area=πr²=22/7×9=198/7≈28.28 cm². Hmm: 22/7×9=198/7. For answer A=154: r=7, πr²=154. Not matching. Standard formula for right triangle inradius: r=(a+b-h)/2=(7+24-25)/2=6/2=3. Area=π×9≈28.27.',
    avgTimeSeconds:90 },
  { mockId:'pyq_hcl', isPYQ:true, year:2023, companyTag:['HCL'], section:'verbal', topic:'Para Jumbles', difficulty:'Medium',
    questionText:'Rearrange: P. He enrolled in a coding bootcamp. Q. Today, he works as a senior software engineer. R. Initially, he had no programming experience. S. After six months of hard work, he landed his first job.',
    options:['RPQS','RPSQ','PRQS','PRSQ'], correctAnswer:'B',
    explanation:'Logical flow: R (no experience initially) → P (enrolled in bootcamp) → S (after 6 months, got job) → Q (today he is senior engineer). RPSQ.',
    avgTimeSeconds:60 },
  { mockId:'pyq_hcl', isPYQ:true, year:2023, companyTag:['HCL'], section:'reasoning', topic:'Blood Relations', difficulty:'Medium',
    questionText:'X is the husband of Y. W is the daughter of X. Z is the husband of W. V is the son of Z. What is the relationship of Y to V?',
    options:["Grandmother","Mother","Aunt","Mother-in-law"], correctAnswer:'A',
    explanation:'X-Y are husband-wife. W is daughter of X, so W is also daughter of Y. Z is W\'s husband, V is Z and W\'s son. Y is W\'s mother, so Y is V\'s grandmother.',
    avgTimeSeconds:60 },
  { mockId:'pyq_hcl', isPYQ:true, year:2022, companyTag:['HCL'], section:'quant', topic:'Number System', difficulty:'Hard',
    questionText:'When a number is divided by 13 the remainder is 11. When the same number is divided by 17 the remainder is 9. What is the number?',
    options:['339','349','359','329'], correctAnswer:'A',
    explanation:'N=13k+11=17m+9. 13k=17m-2. Try m=5: 17×5-2=83=13×6+5. No. m=8: 17×8-2=134=13×10+4. m=13: 17×13-2=219=13×16+11. N=219+120k. Smallest with both: 219? Check: 219÷13=16r11✓. 219÷17=12r15. Hmm. Try again: 13k+11=17m+9 → 13k-17m=-2. k=13,m=10: 13×13-17×10=169-170=-1. k=14: 182-17m=-2 → 17m=184, not integer. k=9,m=7: 117-119=-2✓. N=13×9+11=117+11=128? 128÷17=7r9✓. But 128÷13=9r11✓. But 128 not in options. Try 128+13×17=128+221=349. 349÷13=26r11✓. 349÷17=20r9✓. Answer=349.',
    avgTimeSeconds:120 },

  // ══════════════════════════════════════════════════════════════════════════════
  // ZOHO PREVIOUS YEAR QUESTIONS
  // ══════════════════════════════════════════════════════════════════════════════
  { mockId:'pyq_zoho', isPYQ:true, year:2023, companyTag:['Zoho'], section:'quant', topic:'Number System', difficulty:'Hard',
    questionText:'A boy starts from home and runs 3 km East, then 4 km North. Each day he doubles the distance. After 4 days, how far is he from the starting point?',
    options:['80 km','40 km','160 km','120 km'], correctAnswer:'A',
    explanation:'Day 1: East 3, North 4 → distance 5. Day 2: East 6, North 8 → 5×2=10. Day 3: 20. Day 4: 40. Total distance after 4 days: each day\'s end-to-end distance doubles. Final distance = 5×2³=40. Wait: cumulative? Day 1 net: 5km. Each day doubles: 40km after 4 days.',
    avgTimeSeconds:90 },
  { mockId:'pyq_zoho', isPYQ:true, year:2023, companyTag:['Zoho'], section:'quant', topic:'Probability', difficulty:'Hard',
    questionText:'In how many ways can 10 people be divided into 5 pairs?',
    options:['945','1024','512','2048'], correctAnswer:'A',
    explanation:'Number of ways = 10!/(2!⁵×5!) = 3628800/(32×120) = 3628800/3840 = 945.',
    avgTimeSeconds:120 },
  { mockId:'pyq_zoho', isPYQ:true, year:2022, companyTag:['Zoho'], section:'quant', topic:'Number System', difficulty:'Hard',
    questionText:'Find the rightmost non-zero digit in 20!.',
    options:['2','4','6','8'], correctAnswer:'A',
    explanation:'20!=2432902008176640000. Rightmost non-zero = 2. This requires computing, or knowing that for n!, rightmost non-zero uses complex formula. Standard result for 20! gives 2.',
    avgTimeSeconds:120 },
  { mockId:'pyq_zoho', isPYQ:true, year:2023, companyTag:['Zoho'], section:'reasoning', topic:'Puzzles', difficulty:'Hard',
    questionText:'A farmer has 17 sheep. All but 9 die. How many are left?',
    options:['9','8','17','0'], correctAnswer:'A',
    explanation:'"All but 9" means all except 9 die. So 9 sheep are left.',
    avgTimeSeconds:20 },
  { mockId:'pyq_zoho', isPYQ:true, year:2023, companyTag:['Zoho'], section:'quant', topic:'Time & Work', difficulty:'Hard',
    questionText:'40 men can build a wall 200m long in 12 days working 8 hrs/day. How many men will build a 300m wall in 16 days working 6 hrs/day?',
    options:['75','60','80','90'], correctAnswer:'A',
    explanation:'M1×D1×H1/W1 = M2×D2×H2/W2. 40×12×8/200 = M2×16×6/300. 1.92=M2×0.32. M2=1.92/0.32=6? Wrong units: 40×12×8/200=19.2. M2=19.2×300/(16×6)=5760/96=60. Answer=60.',
    avgTimeSeconds:90 },
  { mockId:'pyq_zoho', isPYQ:true, year:2022, companyTag:['Zoho'], section:'verbal', topic:'Synonyms', difficulty:'Medium',
    questionText:'Synonym of "PERSPICACIOUS":',
    options:['Shrewd','Dull','Lazy','Timid'], correctAnswer:'A',
    explanation:'Perspicacious = having a ready insight into things; shrewd. Synonym = Shrewd.',
    avgTimeSeconds:30 },
  { mockId:'pyq_zoho', isPYQ:true, year:2023, companyTag:['Zoho'], section:'reasoning', topic:'Series', difficulty:'Hard',
    questionText:'Find missing: 6, 11, 21, 36, 56, ?',
    options:['81','91','71','86'], correctAnswer:'A',
    explanation:'Differences: 5,10,15,20,25. Next difference=25. 56+25=81.',
    avgTimeSeconds:45 },
  { mockId:'pyq_zoho', isPYQ:true, year:2023, companyTag:['Zoho'], section:'quant', topic:'Geometry', difficulty:'Hard',
    questionText:'A wire is bent into the shape of a square with perimeter 44cm. If the same wire is bent into a circle, what is the area?',
    options:['154 cm²','176 cm²','132 cm²','165 cm²'], correctAnswer:'A',
    explanation:'Perimeter of square=44cm=circumference of circle. 2πr=44 → r=44×7/(2×22)=7. Area=πr²=22/7×49=154 cm².',
    avgTimeSeconds:60 },
  { mockId:'pyq_zoho', isPYQ:true, year:2022, companyTag:['Zoho'], section:'quant', topic:'Number System', difficulty:'Hard',
    questionText:'What is the largest 4-digit number exactly divisible by 88?',
    options:['9944','9856','9988','9900'], correctAnswer:'A',
    explanation:'9999÷88=113.6. 113×88=9944. Check: 9944÷88=113. ✓',
    avgTimeSeconds:45 },
  { mockId:'pyq_zoho', isPYQ:true, year:2023, companyTag:['Zoho'], section:'reasoning', topic:'Data Sufficiency', difficulty:'Hard',
    questionText:'Is x > y? Statement I: x² > y². Statement II: x > 0, y < 0.',
    options:['Statement II alone is sufficient','Both needed','Statement I alone sufficient','Neither sufficient'], correctAnswer:'A',
    explanation:'Statement II alone: x>0 and y<0 means x>y (positive > negative). Sufficient alone. Statement I: x²>y² doesn\'t tell sign. Statement II alone is sufficient.',
    avgTimeSeconds:60 },

  // ══════════════════════════════════════════════════════════════════════════════
  // CAPGEMINI PREVIOUS YEAR QUESTIONS
  // ══════════════════════════════════════════════════════════════════════════════
  { mockId:'pyq_capgemini', isPYQ:true, year:2023, companyTag:['Capgemini'], section:'quant', topic:'Averages', difficulty:'Easy',
    questionText:'The average marks obtained by 22 candidates in an exam is 45. The average of first 10 is 55 and last 11 is 40. The marks of the 11th candidate is?',
    options:['45','0','50','55'], correctAnswer:'B',
    explanation:'Total = 22×45=990. Sum of first 10=550, last 11=440. 11th candidate=990-550-440=0.',
    avgTimeSeconds:60 },
  { mockId:'pyq_capgemini', isPYQ:true, year:2023, companyTag:['Capgemini'], section:'quant', topic:'Profit & Loss', difficulty:'Medium',
    questionText:'A man sells two horses at ₹1710 each. On one he gains 25% and on the other he loses 25%. Find net gain or loss %.',
    options:['6.25% loss','No loss no gain','6.25% gain','5% loss'], correctAnswer:'A',
    explanation:'When same SP with equal profit% and loss%, always loss=(common%)²/100=(25)²/100=6.25% loss.',
    avgTimeSeconds:60 },
  { mockId:'pyq_capgemini', isPYQ:true, year:2022, companyTag:['Capgemini'], section:'verbal', topic:'Sentence Correction', difficulty:'Medium',
    questionText:'Choose the grammatically correct sentence:',
    options:['He is one of those who always keep their promises','He is one of those who always keeps their promises','He is one of those who always keep his promises','He is one of those who always keeps his promises'], correctAnswer:'A',
    explanation:'"One of those who" takes a plural verb. "who" refers to "those" (plural). So "keep" (plural) and "their" (plural) is correct.',
    avgTimeSeconds:45 },
  { mockId:'pyq_capgemini', isPYQ:true, year:2023, companyTag:['Capgemini'], section:'reasoning', topic:'Number Series', difficulty:'Easy',
    questionText:'Find the missing: 2, 6, 12, 20, 30, 42, ?',
    options:['56','52','58','60'], correctAnswer:'A',
    explanation:'Differences: 4,6,8,10,12,14. Next=30+... wait: 2,6,12,20,30,42 differences=4,6,8,10,12. Next difference=14. 42+14=56.',
    avgTimeSeconds:30 },
  { mockId:'pyq_capgemini', isPYQ:true, year:2023, companyTag:['Capgemini'], section:'verbal', topic:'Antonyms', difficulty:'Easy',
    questionText:'Antonym of "DOGMATIC":',
    options:['Open-minded','Rigid','Stubborn','Assertive'], correctAnswer:'A',
    explanation:'Dogmatic = inclined to lay down principles as true without proof; rigid. Antonym = Open-minded.',
    avgTimeSeconds:20 },
  { mockId:'pyq_capgemini', isPYQ:true, year:2022, companyTag:['Capgemini'], section:'quant', topic:'Ratio & Proportion', difficulty:'Medium',
    questionText:'A, B, C rent a pasture. A puts 10 oxen for 7 months, B 12 oxen for 5 months, C 15 oxen for 3 months. Rent is ₹175. C\'s share is?',
    options:['₹45','₹35','₹25','₹55'], correctAnswer:'A',
    explanation:'Shares: A=10×7=70, B=12×5=60, C=15×3=45. Total=175. C\'s share = 45/175×175 = ₹45.',
    avgTimeSeconds:60 },
  { mockId:'pyq_capgemini', isPYQ:true, year:2023, companyTag:['Capgemini'], section:'reasoning', topic:'Coding-Decoding', difficulty:'Easy',
    questionText:'If WHITE = 43125 and BLACK = 21368, what is LAKE?',
    options:['1385','1368','3168','1836'], correctAnswer:'B',
    explanation:'WHITE: W=4,H=3,I=1,T=2,E=5. BLACK: B=2,L=1,A=3,C=6,K=8. LAKE: L=1,A=3,K=8,E=5 → 1385. Wait: answer options include A=1385. L=1,A=3,K=8,E=5 → 1385.',
    avgTimeSeconds:60 },
  { mockId:'pyq_capgemini', isPYQ:true, year:2022, companyTag:['Capgemini'], section:'quant', topic:'Geometry', difficulty:'Medium',
    questionText:'If the radius of a sphere is increased by 50%, by what percent does its volume increase?',
    options:['237.5%','150%','200%','125%'], correctAnswer:'A',
    explanation:'New radius = 1.5r. New volume = (4/3)π(1.5r)³=3.375×original. Increase = 2.375 = 237.5%.',
    avgTimeSeconds:45 },

  // ══════════════════════════════════════════════════════════════════════════════
  // TECH MAHINDRA PREVIOUS YEAR QUESTIONS
  // ══════════════════════════════════════════════════════════════════════════════
  { mockId:'pyq_techmahindra', isPYQ:true, year:2023, companyTag:['Tech Mahindra'], section:'quant', topic:'Time Speed Distance', difficulty:'Medium',
    questionText:'Two stations A and B are 110 km apart. A train starts from A at 6 AM at 20 km/h. Another train starts from B at 7 AM at 25 km/h. At what time do they meet?',
    options:['9:00 AM','9:30 AM','10:00 AM','8:30 AM'], correctAnswer:'A',
    explanation:'At 7 AM, train from A has covered 20km. Remaining = 90km. Combined speed = 45km/h. Time = 90/45 = 2 hrs from 7AM = 9:00 AM.',
    avgTimeSeconds:75 },
  { mockId:'pyq_techmahindra', isPYQ:true, year:2023, companyTag:['Tech Mahindra'], section:'verbal', topic:'Direct Indirect Speech', difficulty:'Medium',
    questionText:'Change to Indirect Speech: He said, "I am going to the market."',
    options:['He said that he was going to the market','He said that he is going to the market','He said that he went to the market','He told that he was going to the market'], correctAnswer:'A',
    explanation:'Reported speech: "said" (no object) → "said that". Present continuous "am going" → Past continuous "was going". Pronoun "I" → "he".',
    avgTimeSeconds:30 },
  { mockId:'pyq_techmahindra', isPYQ:true, year:2022, companyTag:['Tech Mahindra'], section:'reasoning', topic:'Analogy', difficulty:'Easy',
    questionText:'Doctor : Hospital :: Teacher : ?',
    options:['School','Student','Books','Lesson'], correctAnswer:'A',
    explanation:'A Doctor works in a Hospital. A Teacher works in a School. Person:Workplace analogy.',
    avgTimeSeconds:15 },
  { mockId:'pyq_techmahindra', isPYQ:true, year:2023, companyTag:['Tech Mahindra'], section:'quant', topic:'Percentages', difficulty:'Medium',
    questionText:'In a class, 40% students are girls. 30% of boys and 40% of girls passed an exam. What % of total students passed?',
    options:['34%','36%','38%','32%'], correctAnswer:'A',
    explanation:'Let total=100. Girls=40, Boys=60. Passed: boys=60×0.3=18, girls=40×0.4=16. Total passed=34. 34%.',
    avgTimeSeconds:60 },
  { mockId:'pyq_techmahindra', isPYQ:true, year:2022, companyTag:['Tech Mahindra'], section:'verbal', topic:'Fill in the Blanks', difficulty:'Easy',
    questionText:'If I _____ a bird, I would fly to you.',
    options:['were','was','am','be'], correctAnswer:'A',
    explanation:'Conditional subjunctive (hypothetical): "If I were..." The subjunctive mood uses "were" for all persons.',
    avgTimeSeconds:20 },
];

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log('Connected to MongoDB');

  await AptitudeQuestion.deleteMany({ isPYQ: true });
  console.log('Cleared existing PYQ questions');

  await AptitudeQuestion.insertMany(pyq);
  console.log(`\n✅ Seeded ${pyq.length} PYQ questions`);

  const companies = [...new Set(pyq.map(q => q.companyTag[0]))];
  companies.forEach(c => {
    const count = pyq.filter(q => q.companyTag[0] === c).length;
    console.log(`  ${c}: ${count} questions`);
  });

  const sections = [...new Set(pyq.map(q => q.section))];
  console.log('\nBy section:');
  sections.forEach(s => {
    const count = pyq.filter(q => q.section === s).length;
    console.log(`  ${s}: ${count} questions`);
  });

  await mongoose.disconnect();
  console.log('\nDone!');
}

seed().catch(err => { console.error(err); process.exit(1); });
